update json for localize
hiroyuki-ichikawa/covid19 pull request #112
Opened 2020-07-10 13:35 UTC by jandknagaya

i23 i26

## 👏 解決する issue / Resolved Issues
- close #23 
- close #26

## 📝 関連する issue / Related Issues
- #0
- #0

## ⛏ 変更内容 / Details of Changes

多言語対応用の　assets/localize 下の　jsonファイルへ追加

## 📸 スクリーンショット / Screenshots

![エビデンス](https://user-images.githubusercontent.com/65159906/87160274-b0fb6000-c2fd-11ea-9ed2-bf32aec4b83e.png)

2020-07-12 01:26 UTC, aktnk requested changes
いつくかコメントしていますので、ご確認の上、見直しをお願いします。

（補足）Google翻訳を使い再翻訳すると、翻訳結果がどんどん変化していってしまします。
そんな場合「安定しない」と私はコメントしました。
そんな時、別の翻訳サービスを使って確認してみてください。
私は、例えば、Excite翻訳を使い、再翻訳にチェックをして確認しています。

2020-07-12 01:26 UTC, aktnk commented on assets/locales/en.json
> +  "西部保健所管内": "Inside the Western Health Centre",
西部保健所管内のみ、Centreになっています。

2020-07-12 01:26 UTC, aktnk commented on assets/locales/en.json
> +  "県外": "outside the prefecture",
県外のみoutsideとoが小文字になっています。

2020-07-12 01:26 UTC, aktnk commented on assets/locales/ko.json
> +  "県外": "현",
県外は”현 외”、もしくは”시즈오카 현 외”では？

2020-07-12 01:26 UTC, aktnk commented on assets/locales/zh_CN.json
> +  "中部保健所管内": "在中心卫生院的管辖范围内",
Google翻訳ではいろいろバラつくようです。
Excite翻訳では下記のように安定します。
西部保健所管内＝西部保健所の管轄範囲内⇒西部保健所管辖范围内
東部保健所管内＝東部保健所の管轄範囲内⇒东部保健所管辖范围内
中部保健所管内＝中部保健所の管轄範囲内⇒中部保健所管辖范围内

2020-07-12 01:26 UTC, aktnk commented on assets/locales/zh_TW.json
> +  "中部保健所管内": "在中心衛生院的管轄範圍內",
Excite翻訳で同様にすると
西部保健所管内⇒西部保健所管轄範圍內
東部保健所管内⇒東部保健所管轄範圍內
中部保健所管内⇒中部保健所管轄範圍內

2020-07-12 01:40 UTC, aktnk commented
なお、PR時に記入する定型フォーマット内に下記の修正を行いました。
- 今回の修正でcloseできる issue を2つ追加(aktnk#25,aktnk#33)
- issue番号の前に"aktnk"を追加し、aktnkのissue番号に変更
- 関連する項目は特にないのでリストを削除
- 変更内容を見直した

2020-07-13 00:46 UTC, hrsano645 commented
レビューステータスは付けずに見てます。 @aktnk さんと同じで、修正してもらえればと思います。（PRのdescription修正ありがとうございます！）

@jandknagaya さんのPRを出してるブランチ（ https://github.com/jandknagaya/covid19/tree/hotfix/i23i26-transaction-asserts-locales ）で修正すれば、自動的にここのPRも更新されるので、そのまま作業してください。

2020-07-13 13:54 UTC, aktnk requested changes
何度も指摘してまい、申し訳ありません（最初に気が付いていればよかったのですが）。
英語と、韓国語の指摘した部分について、間違っていると思われますので、確認と修正をお願いします。

2020-07-13 13:54 UTC, aktnk commented on assets/locales/en.json
> +  "中部保健所管内": "In the Central Health Center",
良く考えてみると、現状では保健所内という意味になってしまうと思います。
例えば、以下のようになるのかな？
Jurisdiction in the East Health Center 東部保健所管内
Jurisdiction in the West Health Center　西部保健所管内
Jurisdiction in the Central Health Center　中部保健所管内

2020-07-13 13:54 UTC, aktnk commented on assets/locales/ko.json
> +  "県外": "현외",
スペースにも意味があるようで、
"현외"ではなく"현 외"ではないでしょうか？

2020-07-14 01:23 UTC, jandknagaya commented on assets/locales/en.json
> +  "中部保健所管内": "In the Central Health Center",
確かに！　insideだと、内側という意味になってしまいますね。
ご指摘ありがとうございました。修正します。

2020-07-14 01:27 UTC, jandknagaya commented on assets/locales/ko.json
> +  "県外": "현외",
韓国語は全くわからないので、おっしゃる通りに修正します。
韓国語はこのサイトがおすすめと書いてあったので、ここで変換したまんまに使っていました。
https://papago.naver.com/

2020-07-14 13:20 UTC, aktnk approved these changes
お疲れ様でした。
確認しました。問題ありません。

2020-07-15 02:31 UTC, hrsano645 commented
mergeしちゃいますね。 @jandknagaya OSS初コミットおめです🎉

2020-07-15 02:32 UTC, merged