多言語対応（浜松市の区の追加）
hiroyuki-ichikawa/covid19 pull request #117
Opened 2020-07-26 03:36 UTC by jandknagaya

modefied: asserts/locales/XXXX.json(6)

## 👏 解決する issue / Resolved Issues
- close #37

## ⛏ 変更内容 / Details of Changes

- asserts/localesのJsonファイルの更新

## 📸 スクリーンショット / Screenshots

![6_エビデンス](https://user-images.githubusercontent.com/65159906/88470811-2ee57b00-cf3c-11ea-8aa3-ff4a0ed4077e.JPG)

2020-07-26 11:38 UTC, aktnk requested changes
多言語対応の更新ありがとうございます。
３点ほど確認して頂きたく、お願いいたします。
①PR時の定型フォーマットの「解決する」欄、close #37 では、hiroyuki-ichikawaリポジトリの#37を示してしまいます。他の書き方を参考に見直してください。
残りの2点は下記になります。

2020-07-26 11:38 UTC, aktnk commented on assets/locales/ja-Hira.json
> +  "浜松市浜北区": "浜松市浜北区(はままつし はなきたく)",
「はなきたく」⇒「はまきたく」ではありませんか？

2020-07-26 11:38 UTC, aktnk commented on assets/locales/ko.json
> +  "浜松市天竜区": "하마 마츠시 덴류구 ",
最後の半角スペース要りますか？

2020-07-26 13:27 UTC, jandknagaya commented on assets/locales/ja-Hira.json
> +  "浜松市浜北区": "浜松市浜北区(はままつし はなきたく)",
おっしゃる通りです。すみません。

2020-07-26 13:27 UTC, jandknagaya commented on assets/locales/ko.json
> +  "浜松市天竜区": "하마 마츠시 덴류구 ",
修正します。

2020-07-26 13:38 UTC, jandknagaya commented on assets/locales/ko.json
> +  "浜松市天竜区": "하마 마츠시 덴류구 ",
削除します。

2020-07-27 00:34 UTC, jandknagaya commented
ご指摘のところは修正しましたので、みていただいていいでしょうか？
この修正量でミスしててお恥ずかしい。お手数をおかけしてすみません。

2020-07-27 14:42 UTC, aktnk approved these changes
確認しました。
問題ありません。

2020-07-27 14:43 UTC, merged