「お知らせ」の注意書きの多言語対応
hiroyuki-ichikawa/covid19 pull request #126
Opened 2020-11-28 10:12 UTC by jandknagaya

## 👏 解決する issue / Resolved Issues
- close aktnk#45

## 📝 関連する issue / Related Issues
- aktnk#43

## ⛏ 変更内容 / Details of Changes
お知らせの注意書き
「本ページの数値は、公表済みの数字をベースとしているため、実際の入院者数等とは異なる場合があります」の多言語対応
※以下の多言語対応は未確定のため実施しない
「検査検体採取実施人数」
「（注）検体を採取した日を基準とする」
「保健所が行政検査として行った検体採取人数」
「医療機関等が行政検査として行った検体採取人数」

## 📸 スクリーンショット / Screenshots
![エビデンス①](https://user-images.githubusercontent.com/65159906/100499480-5cbe2300-31ad-11eb-9d2a-0fb6772a71af.png)
![エビデンス②](https://user-images.githubusercontent.com/65159906/100499482-5f207d00-31ad-11eb-80d0-c8127fe8096c.png)

2020-11-28 13:28 UTC, hrsano645 requested changes
コード自体は動くコードで、コードの書き方に関してエラーが出ている部分の修正がされれば大丈夫だと思います。

2020-11-28 13:28 UTC, hrsano645 commented on components/WhatsNew.vue
> +        <span class="WhatsNew-list-item-message-warning">{{ $t('本ページの数値は、公表済みの数値をベースとしているため、実際の入院患者数等とは異なる場合があります') }}</span>
コミット時に、自動的にプログラムのコードのチェックが入ってます。
プログラム的には通るけど、良くないコードの書き方もチェックする機能があって、それに引っかかってるようです。(eslintがそういうツールです）

その部分をこれに変えてもらえれれば多分通ると思います。

```
        <span class="WhatsNew-list-item-message-warning">
          {{
            $t(
              '本ページの数値は、公表済みの数値をベースとしているため、実際の入院患者数等とは異なる場合があります'
            )
          }}
        </span>
```

2020-11-29 11:32 UTC, jandknagaya commented on components/WhatsNew.vue
> +        <span class="WhatsNew-list-item-message-warning">{{ $t('本ページの数値は、公表済みの数値をベースとしているため、実際の入院患者数等とは異なる場合があります') }}</span>
レビューありがとうございました。
修正しました。
ついでに　yarn lint:fix も試してみました(^.^)

2020-12-01 14:40 UTC, aktnk requested changes
先にも書きましたが、ESLintエラーを回避するため、下記のように修正お願いします。
```
      <li class="WhatsNew-list-item WhatsNew-list-item-message">
        <span class="WhatsNew-list-item-message-warning">{{
          $t(
            '本ページの数値は、公表済みの数値をベースとしているため、実際の入院患者数等とは異なる場合があります'
          )
        }}</span>
      </li>
```

2020-12-01 14:40 UTC, aktnk commented on components/WhatsNew.vue
> +		) }}</span>
下記のように変更をお願いします。
```
        <span class="WhatsNew-list-item-message-warning">{{
          $t(
            '本ページの数値は、公表済みの数値をベースとしているため、実際の入院患者数等とは異なる場合があります'
          )
        }}</span>
```

2020-12-02 12:39 UTC, jandknagaya commented on components/WhatsNew.vue
> +		) }}</span>
レビューありがとうございます。
お手数をおかけしました。

2020-12-06 22:04 UTC, hrsano645 commented on components/WhatsNew.vue
> +		) }}</span>
修正確認済みです👍

2020-12-06 22:05 UTC, hrsano645 commented
@jandknagaya ありがとうございます！レビューしたのでmergeします。

2020-12-06 22:06 UTC, merged