オープンデータの検査件数⇒検査人数の変更に伴うサイトの表記名の修正
hiroyuki-ichikawa/covid19 pull request #134
Opened 2020-12-26 09:47 UTC by jandknagaya

表記名変更にあわせて、多言語対応。

## 👏 解決する issue / Resolved Issues
- close aktnk#53

## 📝 関連する issue / Related Issues

## ⛏ 変更内容 / Details of Changes
オープンデータの集計内容の変更（検査件数の集計⇒検査人数の集計）に伴う表記の変更。
表記変更にあわせて多言語対応。

- 変更内容
旧：検査実施件数　
新：検体採取実施人数

旧：（注）検査結果の判定日を基準とする
新：（注）検体を採取した日を基準とする

旧：（注）同一の対象者について複数の検体を検査する場合あり
新：（注）同一の対象者について複数の検体を検査する場合あり（11月30日までは件数、12月1日以降は人数を集計）

旧：地方衛生研究所が行った検査件数
新：保健所が行政検査として行った検体採取人数

旧：医療機関等が行った検査件数
新：医療機関などが行政検査として行った検体採取人数

（棒グラフのマウスオーバー時に表示される説明）
旧：地方衛生研究所　
新：保健所　

## 📸 スクリーンショット / Screenshots

- 表記変更
![累計](https://user-images.githubusercontent.com/65159906/103149196-ae58ce00-47aa-11eb-89e4-ddf7e01812f2.PNG)
![日別_日本語](https://user-images.githubusercontent.com/65159906/103149199-b153be80-47aa-11eb-9edd-56cdf3c67235.PNG)

- 多言語対応
![日別_en](https://user-images.githubusercontent.com/65159906/103149158-4d30fa80-47aa-11eb-8ec0-6e0141d6ac4e.PNG)
![日別_ko](https://user-images.githubusercontent.com/65159906/103149159-502beb00-47aa-11eb-81ea-b5d2fb1f00e5.PNG)

2020-12-26 12:07 UTC, aktnk commented on assets/locales/en.json
> +  "医療機関などが行政検査として行った検体採取人数": "Number of people who have conducted administrative inspections at medical institutions and other institutions",
"医療機関など"となっています。
元々、”等”でしたが”など”とした理由はありますか？

2020-12-26 12:20 UTC, aktnk commented on assets/locales/en.json
> +  "（注）検体を採取した日を基準とする": "(Note) Based on the date when the test.",
メトロ版と同様に、下記のようにしませんか？
”(Note) Based on the date of sample collection."

2020-12-26 12:22 UTC, aktnk commented on assets/locales/en.json
> +  "保健所が行政検査として行った検体採取人数": "Number of people for whom the health center conducted administrative inspections",
下記と使っている単語を合わせて、
"Number of samples collected by the health center as administrative tests"
としませんか？

2020-12-26 12:23 UTC, aktnk commented on assets/locales/ja-Hira.json
> +  "医療機関などが行政検査として行った検体採取人数": "病院等（びょういんなど）で行政検査（ぎょうせいけんさ）をした人数（にんずう）",
https://github.com/hiroyuki-ichikawa/covid19/pull/134/files#r548976459

2020-12-26 12:23 UTC, aktnk commented on assets/locales/ja.json
> +  "医療機関などが行政検査として行った検体採取人数": "医療機関などが行政検査として行った検体採取人数",
https://github.com/hiroyuki-ichikawa/covid19/pull/134/files#r548976459

2020-12-26 12:24 UTC, aktnk commented on assets/locales/ko.json
> +  "医療機関などが行政検査として行った検体採取人数": "의료기관이 실시한 검사 수",
https://github.com/hiroyuki-ichikawa/covid19/pull/134/files#r548976459

2020-12-26 12:24 UTC, aktnk commented on assets/locales/zh_CN.json
> +  "医療機関などが行政検査として行った検体採取人数": "医疗机构等进行的检查件数",
https://github.com/hiroyuki-ichikawa/covid19/pull/134/files#r548976459

2020-12-26 12:24 UTC, aktnk commented on assets/locales/zh_TW.json
> +  "医療機関などが行政検査として行った検体採取人数": "在醫療機構等實施行政檢查的人的數",
https://github.com/hiroyuki-ichikawa/covid19/pull/134/files#r548976459

2020-12-26 12:26 UTC, aktnk commented on components/TimeStackedBarChart.vue
>            {{ $t('（注）同一の対象者について複数の検体を検査する場合あり') }}
”（11月30日までは件数、12月1日以降は人数を集計）”の記述がありません。

2020-12-26 12:35 UTC, aktnk requested changes
確認しました。
いくつか修正をお願いします。

尚、（注）の2つ目に、”（11月30日までは件数、12月1日以降は人数を集計）”を追記すればよいという基準でレビューを記載しました。

2020-12-26 12:47 UTC, jandknagaya commented on assets/locales/en.json
> +  "（注）検体を採取した日を基準とする": "(Note) Based on the date when the test.",
了解です

2020-12-26 12:48 UTC, jandknagaya commented on assets/locales/en.json
> +  "保健所が行政検査として行った検体採取人数": "Number of people for whom the health center conducted administrative inspections",
了解です

2020-12-26 12:53 UTC, jandknagaya commented
@aktnk さん、レビューありがとうございました。
Error: [eslint] reported by reviewdog 　調査してわからなかったら教えてください。

2020-12-26 13:26 UTC, aktnk commented on components/TestedCasesTable.vue
> +        {{ $t('検体採取実施人数') }}
この修正、必要ですか？

2020-12-28 03:10 UTC, jandknagaya commented on assets/locales/en.json
> +  "医療機関などが行政検査として行った検体採取人数": "Number of people who have conducted administrative inspections at medical institutions and other institutions",
等にします

2020-12-28 05:37 UTC, jandknagaya commented on components/TestedCasesTable.vue
> +        {{ $t('検体採取実施人数') }}
必要ありませんでした

2020-12-28 12:11 UTC, aktnk commented on components/TimeStackedBarChart.vue
> +            )
1行で、書けば良いのでは？
”{{ $t('（注）検体を採取した日を基準とする') }}”

2020-12-28 12:13 UTC, aktnk commented on components/cards/TestedNumberCard.vue
> +	     ),
ここも、前回のように一行で書けば良いと思います。

2020-12-28 12:16 UTC, aktnk commented on components/cards/TestedNumberCard.vue
> +    const inspectionsDataLabels =  [this.$t('保健所'), this.$t('医療機関等')]
ここは“="と"["の間に、スペース1個で良いのでは？

2020-12-28 12:25 UTC, aktnk requested changes
esling_errorの対処についてコメントしました。
ほんの些細なことですが、修正をお願いします。

⇒ windowsならgit bash使えば、Githubにpushした際、勝手に修正してくれますよ。
　もしくは、
　git bashで、yarn run eslint './**/*.{js,ts,vue}' --fix を実行すれば、修正してくれますよ。

2020-12-28 15:04 UTC, aktnk commented
要件と照らし合わせ、動作確認しました。
下記の修正が必要です。
- グラフのタイトルは、「検査（検体採取）実施人数」です。
- マウスオーバー時に表示される数値の単位は「人」です。
![Inkednagaya_2_LI](https://user-images.githubusercontent.com/13390370/103223334-53b9a080-4969-11eb-91e3-84133597eb87.jpg)
![Inkednagaya_1_LI](https://user-images.githubusercontent.com/13390370/103223336-574d2780-4969-11eb-8f6d-589b101d27d1.jpg)

2020-12-28 15:09 UTC, aktnk requested changes
タイトルと、単位の修正をお願いします。

2020-12-29 03:07 UTC, aktnk commented on components/ConfirmedCasesCard.vue
> +    <template v-slot:button />
eslint_errorがここでも出ているかもしれませんが、下記の点から、
本件の修正に含めないことにしたいと思います。
・もともとの狙いとは関係のないファイルの修正である。
・このカードの実装はどこでも使われていない

2020-12-29 03:09 UTC, aktnk requested changes
悩みましたが、本件の修正は除いて下さい。
お手数ですが、お願いします。

2020-12-30 00:36 UTC, jandknagaya commented
> 悩みましたが、本件の修正は除いて下さい。
> お手数ですが、お願いします。

承知しました。

2020-12-31 02:57 UTC, aktnk commented
確認しました。OKでした。
以下にキャプチャーを載せておきます。
- 日本語：日別
![image](https://user-images.githubusercontent.com/13390370/103391457-f423e680-4b5c-11eb-90b1-6d167fd8390a.png)
- 日本語：累計
![image](https://user-images.githubusercontent.com/13390370/103391470-0736b680-4b5d-11eb-92d7-558dfd143bd5.png)
- 英語：日別
![image](https://user-images.githubusercontent.com/13390370/103391552-672d5d00-4b5d-11eb-8eb5-0e39c24de803.png)
- 簡体中文：日別ツールチップ１
![image](https://user-images.githubusercontent.com/13390370/103391627-ba9fab00-4b5d-11eb-9648-f88c8013701f.png)
- 繁体中文：累計ツールチップ２
![image](https://user-images.githubusercontent.com/13390370/103391710-2c77f480-4b5e-11eb-9689-9baa9ea02731.png)
- ハングル：日別
![image](https://user-images.githubusercontent.com/13390370/103391807-824c9c80-4b5e-11eb-8302-513305382483.png)
- やさしい日本語：累計
![image](https://user-images.githubusercontent.com/13390370/103392041-50880580-4b5f-11eb-86c3-e930f604d748.png)

2020-12-31 03:00 UTC, aktnk approved these changes

2020-12-31 03:07 UTC, aktnk commented
**公開に向けての注意点**
オープンデータ側に変更がある場合は、下記辺りに別途対応が必要です。
https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/blob/f22462f2ba204426e96331df6078c467a089418d/patients.py#L429-L430

2021-01-01 08:31 UTC, jandknagaya commented
@aktnk さん、何度もお手数をおかけして申し訳ありません。
丁寧にみていただいてありがとうございます。

2021-01-01 22:14 UTC, hrsano645 commented
@aktnk オープンデータ側の列名が変わったら生成スクリプト側の対応もしてみます。
オープンデータの更新も年明けからってことなので、先に公開しておいて、CSV側が変わったらその時に対応かな😅

2021-01-02 01:56 UTC, aktnk commented
@hrsano645 , @jandknagaya さん
> オープンデータ側の列名が変わったら生成スクリプト側の対応もしてみます。

列名が変わったら、よろしくお願いします。

> オープンデータの更新も年明けからってことなので、先に公開しておいて、CSV側が変わったらその時に対応かな

それでは、本件、developmentブランチにはマージしておきますね。

2021-01-02 02:16 UTC, merged