SSGのローカル確認用に追加
hiroyuki-ichikawa/covid19 pull request #144
Opened 2021-01-09 12:18 UTC by Jyury11

## 👏 解決する issue / Resolved Issues
- close aktnk#58

## 📝 関連する issue / Related Issues
- aktnk#55

## ⛏ 変更内容 / Details of Changes
- 本番環境用のSSGをローカルで確認する為に以下を追加
  - Dockerfile.prod
  - docker-compose-prod.yml

## 📸 スクリーンショット / Screenshots
- コマンド
<img width="682" alt="docker-compose prod" src="https://user-images.githubusercontent.com/52658771/104091181-2b159d00-52bf-11eb-9fbe-08391272eede.png">

- localhost:3000での接続
<img width="840" alt="localhost_3000" src="https://user-images.githubusercontent.com/52658771/104091223-5e582c00-52bf-11eb-93d5-fc23a8500531.PNG">

2021-01-09 13:56 UTC, aktnk commented
動作確認をしましたが、私の環境では、dist配下のコンテンツは表示されず、Nginxのデフォルトコンテンツが表示されてしまいました。
![image](https://user-images.githubusercontent.com/13390370/104093065-8057ab80-52cb-11eb-8965-9ca344012603.png)

私の環境は、Windows10proで、Docker Desktop for Windowsを使っています。
起動しているコンテナに入り、/usr/share/nginx/htmlを確認したところ、
下記のようになっており、distが生成されていない、もしくは、生成されたdistがコピーされていない可能性があります。
![image](https://user-images.githubusercontent.com/13390370/104093244-931eb000-52cc-11eb-8847-a867862a22ac.png)

参考に、docker-compose 実行時のログを掲載しておきます。
![image](https://user-images.githubusercontent.com/13390370/104093290-02949f80-52cd-11eb-8857-be38c769fd16.png)

2021-01-09 13:59 UTC, aktnk commented on Dockerfile.prod
> +CMD ["yarn", "generate:deploy"]
CMDは最後に最後に一度だけ、イメージの実行に使用しますので、
ここでは、RUNを使用するのでは？

2021-01-09 14:00 UTC, aktnk commented on Dockerfile.prod
> +COPY --from=builder /app/dist /usr/share/nginx/html
この次の行で、nginxを起動するようにするのでは？
CMD ["nginx", "-g", "daemon off;"]

2021-01-09 14:09 UTC, aktnk commented on docker-compose-prod.yml
> +    container_name: covid19
既存のdocker-compose up --buildを実行させた状態で、
本、docker-compose -f docker-compose-prod.yml up --buildを実行する可能性も考え、サービス名app、コンテナメイcovid19は別も名前に変更しておきたいと思います。

2021-01-09 14:09 UTC, aktnk requested changes
気になった点をコメントしました。
確認の上、修正をお願いします。

2021-01-09 14:13 UTC, aktnk commented on docker-compose-prod.yml
> +        - 3000:80
port番号も3000から変えておかないと、同時使用できませんね。

2021-01-10 00:37 UTC, Jyury11 commented on Dockerfile.prod
> +CMD ["yarn", "generate:deploy"]
おっしゃる通りですね・・・
コピーを行いたいのはビルド時だから、RUNを使用すべきでした。

2021-01-10 00:39 UTC, Jyury11 commented on Dockerfile.prod
> +COPY --from=builder /app/dist /usr/share/nginx/html
dockerコマンドのみで立ち上げたときにコンテナが落ちてしまいますね・・・
修正しました。

2021-01-10 00:41 UTC, Jyury11 commented on docker-compose-prod.yml
> +    container_name: covid19
同時実行の事を考慮していませんでした・・・
以下のように修正しました。
- サービス名：app_prod
- コンテナ名：covid19_prod

2021-01-10 00:41 UTC, Jyury11 commented on docker-compose-prod.yml
> +        - 3000:80
以下のように修正しました。
- port番号：8080

2021-01-10 00:42 UTC, Jyury11 commented on Dockerfile.prod
> +RUN yarn generate:deploy
CMDからRUNを使用するように修正

2021-01-10 00:43 UTC, Jyury11 commented on Dockerfile.prod
> +CMD ["nginx", "-g", "daemon off;"]
CMDでnginxプロセスを起動するように修正

2021-01-10 00:45 UTC, Jyury11 commented on docker-compose-prod.yml
> +  app_prod:
サービス名を修正
- app → app_prod

2021-01-10 00:46 UTC, Jyury11 commented on docker-compose-prod.yml
> +    container_name: covid19_prod
コンテナ名を修正
- covid19 → covid19_prod

2021-01-10 00:47 UTC, Jyury11 commented on docker-compose-prod.yml
> +        - 8080:80
port番号を修正
- 3000 → 8080

2021-01-10 01:04 UTC, Jyury11 commented
頂いた指摘を確認の上、修正しました。
以下に自環境での動作確認を記載します。
- localhost:8080での接続
<img width="840" alt="localhost_8080" src="https://user-images.githubusercontent.com/52658771/104111859-c8f28180-532a-11eb-8e54-aa1a5c29afa9.PNG">

- nginxコンテナの公開ディレクトリ
<img width="1165" alt="docker_exec" src="https://user-images.githubusercontent.com/52658771/104111873-e293c900-532a-11eb-9483-492384f7d2ba.PNG">

- docker psコマンド実行時
<img width="1165" alt="docker_ps" src="https://user-images.githubusercontent.com/52658771/104111878-f2131200-532a-11eb-9851-efaf13cfaf4b.png">

- docker-composeコマンド実行時
<img width="1920" alt="docker-compose prod" src="https://user-images.githubusercontent.com/52658771/104111881-ffc89780-532a-11eb-86f4-9e1e7b2d9956.png">

2021-01-10 02:19 UTC, hrsano645 commented
@Jyury11 PRありがとうございます！ 
重箱のすみな指摘になってしまいますが、closeするissueにある aktnk#58 は aktnk#59 と思われます。
closeする前に変更しておいてもらえると助かります。（そのままissueがcloseするので）

2021-01-10 02:28 UTC, Jyury11 commented
@hrsano645 さん
タイポしてましたね・・・申し訳ないです。
承知しました。修正いたします。

2021-01-10 02:51 UTC, hrsano645 commented
こちらもdocker-composeで生成されたファイル確認できるようになりました。
nginxでlocalhost:8080でのサーバー動作も確認してます。

2021-01-10 03:06 UTC, aktnk approved these changes
確認しました。
動作も確認できました。
OKです。

2021-01-10 09:59 UTC, merged