「検査陽性者の状況」に自宅療養を追加する（県からの要望）
hiroyuki-ichikawa/covid19 pull request #151
Opened 2021-02-16 05:40 UTC by jandknagaya

それに伴う多言語対応

## 👏 解決する issue / Resolved Issues
- close aktnk#70
- close aktnk#71

## 📝 関連する issue / Related Issues
- データ作成PRG　Issue
  https://github.com/hrsano645/covid19-gen-datajson-shizuokapref/issues/43

## ⛏ 変更内容 / Details of Changes

- オープンデータ側の変更に合わせて、「検査陽性者の状況」の「入院・療養等調整中」を、「自宅療養」「入院等調整中」に分割する
- 上記分割に伴う多言語対応
- ついでに、aktnk#71　簡体中文選択時の「多言語対応選択メニュー」の翻訳を修正

## 📸 スクリーンショット / Screenshots

![検査陽性者の状況の陽性者数内訳アイテム追加](https://user-images.githubusercontent.com/65159906/108022862-bf181880-7064-11eb-86f9-a7f6d0e567ba.png)

![多言語1](https://user-images.githubusercontent.com/65159906/108022878-c5a69000-7064-11eb-9e6c-31dc5e14f450.PNG)

![多言語2](https://user-images.githubusercontent.com/65159906/108022904-d3f4ac00-7064-11eb-9610-356e7041b78c.PNG)

2021-02-16 12:48 UTC, hrsano645 approved these changes
こちらもデータ生成の結果を確認するときに動作チェック済みです。お疲れ様です👍

2021-02-18 01:46 UTC, aktnk requested changes
「自宅療養」の多言語対応ですが、東京都の対策サイトと合わせた方が良いと思います。

2021-02-21 12:41 UTC, aktnk approved these changes
@jandknagaya さん
お待たせしました。
確認完了です。問題ありません。

2021-02-24 11:06 UTC, hrsano645 commented
生成スクリプト側を更新したので、こちらもmergeします。

一時的に開発版のサイトはエラーで生成できないはずですが、定期的なデータ更新の後に再度生成させます。

2021-02-24 11:27 UTC, merged