GitHub Actionsを使ってデータ用のjsonファイル生成と更新を行う(rev2
hiroyuki-ichikawa/covid19 pull request #158
Opened 2021-05-21 07:06 UTC by hrsano645

## 👏 解決する issue / Resolved Issues
- close https://github.com/aktnk/covid19/issues/54

## 📝 関連する issue / Related Issues
- #155 : このPRの前バージョンです。

## ⛏ 変更内容 / Details of Changes

- 普段サーバーで行っている定期更新のスクリプトをGitHub Actions（ワークフロー）で行います
- スケジュール動作として 毎日20時に動作します。なおGitHub ActionsではUTC表記でJSTは-9時間です。（UTC11時に実行されます）
- スケジュール動作以外にもworkflow_dispatch機能で手動実行も可能です。
- development, master双方に実行されます。データ生成後に対策サイトの生成（デプロイ）が動作させる変更もしています。
  - .github/workflows/develop.yml: 対策サイトの開発版を生成
  - .github/workflows/deploy.yml: 対策サイトの本番用を生成
  - .github/workflows/ogp_builder.yml: 対策サイトの本番用で使うOGP画像を生成

2021-05-22 00:49 UTC, hrsano645 commented
この変更で問題になりそうなことの想定とその回答を上げておきます。


Q: GitHub Actions更新が失敗した場合は？

A: スケジュール動作が何らかの問題で失敗した場合は、手動（workflow_dispatch) で起動可能。Actionsが障害で落ちている場合はそのあとに実行すればよいはず

---

Q: 現在定期更新しているサーバー側の影響: サーバー側の定期更新は動かしたままでもいいか？

A: サーバー側（development, master共に）はgit pullした後にデータ更新>commit>pushしていると思っていて、その場合、development, masterの最新を元にcommitされると想定している。データ自体も最新版になっていたらcommit>pushは動かないはずです。

逆にGitHub Actions側が失敗した場合のバックアップにも使えるので、どちらも動かしておいて損はないはず。

---

Q: 現在定期更新しているサーバー側の影響: 逆にGitHub Actions側で問題が起こる可能性は？

A: GitHub Actions側のデータ更新も、最新のdevelopment, masterをcheckoutするので、そのタイミングで最新のデータに更新済みなら、更新されないはずです。

2021-05-22 06:15 UTC, aktnk commented on .github/workflows/data_update.yml
> +  # 毎日20時に実行:GitHub ActionsはUTCなので、JST(UTC-9)の11時に実行
”JSTの11時”　だと　”UTCの2時”　ということになりません？

→　”JSTの20時”に実行させるため、”UTCの11時”に設定

2021-05-22 06:15 UTC, aktnk commented on .github/workflows/data_update.yml
> +    runs-on: ubuntu-latest
ubuntu-latest とすると、Github側で ubuntu システムを更新した際に動作しなくなる可能性があるので、バージョンを明示した方がよいかと思いました。

2021-05-22 06:15 UTC, aktnk commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
actions/checkout@v2 のアクションのとき、name が指定されていません。
checkout from 〇〇等を追加するとよいかと思いました。
尚、この行以下でも同様のようです。

2021-05-22 06:15 UTC, aktnk commented on .github/workflows/deploy.yml
> +    branched: [master]
`branched` は `branches`ではありませんか？
また、前後と記述を合わせるなら、
```
branches:
   - master
```
とするのはどうでしょう？

2021-05-22 06:16 UTC, aktnk commented on .github/workflows/develop.yml
> +    branched: [development]
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361746
に同じ

2021-05-22 06:16 UTC, aktnk commented on .github/workflows/ogp_builder.yml
> +    branched: [master]
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361746
に同じ

2021-05-22 06:17 UTC, aktnk commented on .github/workflows/data_update.yml
> +    runs-on: ubuntu-latest
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361738
に同じ

2021-05-22 06:17 UTC, aktnk commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361741
に同じ

2021-05-22 06:17 UTC, aktnk commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361741
に同じ

2021-05-22 06:18 UTC, aktnk commented on .github/workflows/data_update.yml
> +    runs-on: ubuntu-latest
https://github.com/hiroyuki-ichikawa/covid19/pull/158/files#r637361738
に同じ

2021-05-22 06:21 UTC, aktnk requested changes
レビューコメント記載しました。
いくつか気になる点がありますので、確認お願いします。
動作確認していませんので、もし修正の必要があれば、よろしくお願いします。

2021-05-22 06:32 UTC, hrsano645 commented
@aktnk ありがとうございます。レビュー見直してみます。GitHub Actionsは割と寛容な部分があって、設定がおかしいけどそのまま動いてしまうことがあるので煮詰めるときに困りますｗ

2021-05-22 06:36 UTC, hrsano645 commented on .github/workflows/data_update.yml
> +  # 毎日20時に実行:GitHub ActionsはUTCなので、JST(UTC-9)の11時に実行
逆でしたね。修正します！

2021-05-22 06:40 UTC, hrsano645 commented on .github/workflows/data_update.yml
> +    runs-on: ubuntu-latest
そうですね。固定したほうがPythonのバージョン周りも維持し続けられるので固定します。
Ubuntuの最新バージョンだと20.04なので`ubuntu-20.04`に切り替えます。

2021-05-22 06:48 UTC, hrsano645 commented on .github/workflows/deploy.yml
> +    branched: [master]
> `branched` は `branches`ではありませんか？

その通りでした。

> また、前後と記述を合わせるなら、
> 
> ```
> branches:
>    - master
> ```
> 
> とするのはどうでしょう？

この部分本来だと必要なさそうで、トリガーとなるワークフロー（`datajson update`）だけあればよさそうです。
branchesのオプションは外してみます。

2021-05-22 06:49 UTC, hrsano645 commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
nameあったほうがわかりやすいですね。（コピペしてたので書いてなかったです）
そのままインスパイアさせてもらってnameは 「checkout from covid19-gen-datajson-shizuokapref」とします。

2021-05-23 02:53 UTC, aktnk commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
ここにも、name 記述しません？
- name: Checkout from development branch など

2021-05-23 02:55 UTC, aktnk commented on .github/workflows/data_update.yml
> +      - uses: actions/checkout@v2
ここにも name 追加しません？
`- name: Checkout from master branch `

2021-05-23 02:57 UTC, aktnk requested changes
checkout している箇所で、name が記載されていない箇所がもう2か所あります。
ここにもname 追加しませんか？

2021-05-23 11:32 UTC, hrsano645 commented
ここまでのcommitで実験した結果です。デプロイ結果も確認してみましたがnews.jsonの更新もちゃんとできてました。

- Actions
  - データ更新: https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/actions/runs/868545009
  - developmentのデプロイ: https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/actions/runs/868546733
  - masterのデプロイ: https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/actions/runs/868546732
- デプロイ結果
  - development: https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/tree/24a72250aff6e68be839b7ce8453156524fb25f4
  - master: https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/tree/5095ef60b8c2d01668e18bafc582ec762c430dbb

2021-05-23 11:33 UTC, hrsano645 commented
> checkout している箇所で、name が記載されていない箇所がもう2か所あります。
> ここにもname 追加しませんか？

記載しました！

2021-05-23 12:16 UTC, aktnk approved these changes
私も動作確認とりました。
data.json生成されていました。

2021-05-23 13:19 UTC, hrsano645 commented
@aktnk 動作確認まで！ありがとうございます。mergeします。
スケジュール更新自体もテスト用のリポジトリで動作確認済み（ワークフローとしては失敗はしてますが、commitする必要がないという意味で失敗してます）
https://github.com/hrsano645/test_gha_stopcovid19_shizuoka/actions/runs/868548602

2021-05-23 13:19 UTC, merged